name: shooting_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  #flutter_statusbarcolor: ^0.2.3
  http: 0.13.4
  provider: 5.0.0
  dotted_decoration: 2.0.0
  image_picker: 0.8.4+11
  permission_handler: 9.2.0
  shared_preferences: 2.0.13
  cached_network_image: 3.2.0
  get_it: 7.2.0
  dio: 4.0.4
  fluttertoast: 8.0.9
  photo_view: 0.13.0
  device_info_plus: 4.0.0
  flutter_svg: 1.0.3
  url_launcher: 6.1.0

  # flutter_signin_button: ^2.0.0
  sign_in_with_apple: 4.3.0

  # google_sign_in: ^5.4.2
  # firebase_auth: any


  #  fluttertoast: any


  #  dashed_circle: ^0.0.2
#  modal_gif_picker: ^0.0.1
#  align_positioned: ^3.0.0
#  perfect_freehand: ^1.0.4
#  gallery_media_picker: ^0.0.7
#  image_gallery_saver: ^1.7.1
#  path_provider: ^2.0.9
#  image: ^3.1.3
#  animated_text_kit: ^4.2.1
# ------------------------------
  # cloud_firestore: ^3.1.10
  # firebase_messaging: ^11.2.11
  # firebase_core: ^1.13.1
  # flutter_local_notifications: ^9.4.0


  cloud_firestore: 4.1.0
  google_sign_in: 5.4.2
  firebase_auth: 4.1.4
  firebase_messaging: 14.1.2
  firebase_core: 2.3.0
  flutter_local_notifications: 9.5.2

  # photo_manager: ^2.1.1

  share_plus: 4.0.2
  soundpool: 2.3.0
  clipboard: 0.1.3
  uni_links: 0.5.1
  video_player: 2.3.0
#  rflutter_alert: ^2.0.4

  string_validator: 0.3.0
  html: 0.15.0

  receive_sharing_intent: 1.4.5
  bloc: 8.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
