name: shooting_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  #flutter_statusbarcolor: ^0.2.3
  http: any
  provider: any
  dotted_decoration: ^2.0.0
  image_picker: ^0.8.4+11
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  get_it: ^7.2.0
  dio: ^4.0.4
  flutter_svg: ^1.0.3

  dashed_circle: ^0.0.2
  modal_gif_picker: ^0.0.1
  fluttertoast: ^8.0.9
  align_positioned: ^3.0.0
  perfect_freehand: ^1.0.4
  gallery_media_picker: ^0.0.7
  image_gallery_saver: ^1.7.1
  photo_view: ^0.13.0
  path_provider: ^2.0.9
  image: ^3.1.3
  animated_text_kit: ^4.2.1
  url_launcher: ^6.1.0

  cloud_firestore: ^3.1.10
  firebase_messaging: ^11.2.11
  firebase_core: ^1.13.1
  flutter_local_notifications: ^9.4.0

  share_plus: ^4.0.2
  soundpool: ^2.3.0
  clipboard: ^0.1.3
#  uni_links: ^0.5.1
  video_player: ^2.3.0
  rflutter_alert: ^2.0.4
  story_view: ^0.13.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:

    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-VariableFont_wght.ttf

    - family: B612
      fonts:
        - asset: assets/fonts/B612-Regular.ttf

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf

    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf

    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-Regular.ttf

    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf

    - family: ConcertOne
      fonts:
        - asset: assets/fonts/ConcertOne-Regular.ttf

    - family: YatraOne
      fonts:
        - asset: assets/fonts/YatraOne-Regular.ttf

    - family: OldStandardTT
      fonts:
        - asset: assets/fonts/OldStandardTT-Italic.ttf

    - family: Neonderthaw
      fonts:
        - asset: assets/fonts/Neonderthaw-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: SedgwickAve
      fonts:
        - asset: assets/fonts/SedgwickAve-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf

    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf

    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

    - family: FrederickatheGreat
      fonts:
        - asset: assets/fonts/FrederickatheGreat-Regular.ttf

    - family: ReenieBeanie
      fonts:
        - asset: assets/fonts/ReenieBeanie-Regular.ttf

    - family: BungeeShade
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf

    - family: UnifrakturMaguntia
      fonts:
        - asset: assets/fonts/UnifrakturMaguntia-Regular.ttf