name: shooting_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^8.7.0
  #flutter_statusbarcolor: ^0.2.3
  provider: any
  dotted_decoration: ^2.0.0
  image_picker: ^0.8.4+11
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  get_it: ^7.2.0
  dio: ^4.0.4
  flutter_svg: ^1.0.3

  dashed_circle: ^0.0.2
  story: ^0.6.0
#  stories_editor: 0.1.8
  modal_gif_picker: ^0.0.1
  fluttertoast: ^8.0.9
  align_positioned: ^3.0.0
  perfect_freehand: ^1.0.4
  gallery_media_picker: ^0.0.7
  image_gallery_saver: ^1.7.1
  photo_view: ^0.13.0
  path_provider: ^2.0.9
  image: ^3.1.3
  animated_text_kit: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/khanegreen/
    - images/